AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
